# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConceptInterfataQt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(569, 319)
        Dialog.setBaseSize(QtCore.QSize(567, 365))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../cropped-riscv-favicon-32x32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonSal = QtWidgets.QPushButton(Dialog)
        self.buttonSal.setGeometry(QtCore.QRect(149, 70, 161, 40))
        self.buttonSal.setObjectName("buttonSal")
        self.buttonCod = QtWidgets.QPushButton(Dialog)
        self.buttonCod.setGeometry(QtCore.QRect(6, 70, 140, 40))
        self.buttonCod.setObjectName("buttonCod")
        self.buttonIncFis = QtWidgets.QPushButton(Dialog)
        self.buttonIncFis.setGeometry(QtCore.QRect(3, 3, 140, 23))
        self.buttonIncFis.setObjectName("buttonIncFis")
        self.buttonDel = QtWidgets.QPushButton(Dialog)
        self.buttonDel.setGeometry(QtCore.QRect(149, 3, 161, 23))
        self.buttonDel.setObjectName("buttonDel")
        self.listInput = QtWidgets.QListWidget(Dialog)
        self.listInput.setGeometry(QtCore.QRect(313, 3, 252, 314))
        self.listInput.setObjectName("listInput")
        self.textInstr = QtWidgets.QTextEdit(Dialog)
        self.textInstr.setGeometry(QtCore.QRect(6, 45, 140, 20))
        self.textInstr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textInstr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textInstr.setAcceptRichText(True)
        self.textInstr.setObjectName("textInstr")
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(6, 29, 151, 16))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(6, 110, 221, 21))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(6, 130, 221, 16))
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(6, 150, 261, 16))
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(Dialog)
        self.label5.setGeometry(QtCore.QRect(6, 170, 241, 16))
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(Dialog)
        self.label6.setGeometry(QtCore.QRect(6, 190, 251, 16))
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(Dialog)
        self.label7.setGeometry(QtCore.QRect(6, 210, 281, 16))
        self.label7.setObjectName("label7")
        self.label8 = QtWidgets.QLabel(Dialog)
        self.label8.setGeometry(QtCore.QRect(6, 230, 241, 16))
        self.label8.setObjectName("label8")
        self.label9 = QtWidgets.QLabel(Dialog)
        self.label9.setGeometry(QtCore.QRect(6, 250, 301, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label9.setFont(font)
        self.label9.setTextFormat(QtCore.Qt.PlainText)
        self.label9.setObjectName("label9")
        self.label10 = QtWidgets.QLabel(Dialog)
        self.label10.setGeometry(QtCore.QRect(6, 285, 281, 32))
        self.label10.setObjectName("label10")
        self.buttonInstr = QtWidgets.QPushButton(Dialog)
        self.buttonInstr.setGeometry(QtCore.QRect(149, 29, 161, 38))
        self.buttonInstr.setObjectName("buttonInstr")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Codificator RISC-V RV64I"))
        self.buttonSal.setText(_translate("Dialog", "Salvare în fișier input"))
        self.buttonCod.setText(_translate("Dialog", "Codificare instrucțiune"))
        self.buttonIncFis.setText(_translate("Dialog", "Încărcare fișier"))
        self.buttonDel.setText(_translate("Dialog", "Eliminare conținut"))
        self.label1.setText(_translate("Dialog", "Instrucțiune de codificat"))
        self.label2.setText(_translate("Dialog", "Format instrucțiuni R: op rd, rs1, rs2"))
        self.label3.setText(_translate("Dialog", "Format instrucțiuni I: op rd, rs1, imm"))
        self.label4.setText(_translate("Dialog", "Format instrucțiuni branch: op rs1, rs2, imm"))
        self.label5.setText(_translate("Dialog", "Format instrucțiuni load: op rd, imm(rs1)"))
        self.label6.setText(_translate("Dialog", "Format instrucțiuni store: op rd, imm(rs1)"))
        self.label7.setText(_translate("Dialog", "Format instrucțiuni lui, auipc și jal: op rd, imm"))
        self.label8.setText(_translate("Dialog", "Format instrucțiune jalr: jalr rd, imm(rs1)"))
        self.label9.setText(_translate("Dialog", "Fișier input: Salvare codificare în format explicativ\n"
"big endian"))
        self.label10.setText(_translate("Dialog", "Fișier instruction: Salvare în format little endian \n"
"pentru executare pe procesor"))
        self.buttonInstr.setText(_translate("Dialog", "Salvare în fișier instruction"))
